In [29]:
import joblib
import pandas as pd

In [30]:
model = joblib.load("ipl_model.pkl")
type(model)

sklearn.ensemble._forest.RandomForestClassifier

In [31]:
le_dict = joblib.load("label_encoders.pkl")
type(le_dict)

dict

In [32]:
sample = {
    'batting_team': 'Kolkata Knight Riders',
    'bowling_team': 'Royal Challengers Bangalore',
    'venue': 'M Chinnaswamy Stadium',
    'city': 'Bangalore',
    'toss_winner': 'Royal Challengers Bangalore',
    'toss_decision': 'field',
    'over': 10,
    'ball': 3,
    'runs_total': 1,
    'runs_batter': 1,
    'team_runs': 80,
    'team_wicket': 2
}

sample_df = pd.DataFrame([sample])
sample_df

,batting_team,bowling_team,venue,city,toss_winner,toss_decision,over,ball,runs_total,runs_batter,team_runs,team_wicket
0,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,field,10,3,1,1,80,2

In [33]:
for col in sample_df.columns:
    if col in le_dict:
        sample_df[col] = le_dict[col].transform(sample_df[col])

sample_df

,batting_team,bowling_team,venue,city,toss_winner,toss_decision,over,ball,runs_total,runs_batter,team_runs,team_wicket
0,8,16,23,2,16,1,10,3,1,1,80,2

In [37]:
prediction = model.predict(sample_df)

# Decode result
winner = le_dict['match_won_by'].inverse_transform(prediction)

print("Predicted Winner:", winner[0])
prediction

Predicted Winner: Royal Challengers Bangalore

array([16])